package eu.dedalus.prescriptionsolver;
import eu.dedalus.prescriptionmodel.Procedure;
import eu.dedalus.prescriptionsolver.Prescription;
import eu.dedalus.prescriptionsolver.PrescriptionEntity;
import eu.dedalus.prescriptionmodel.CommonDataInterface;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class PrescriptionProcedure extends PrescriptionEntity implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Procedure procedure;

	public PrescriptionProcedure() {
	    super(null);
	}
	
	public PrescriptionProcedure(Procedure procedure, Prescription prescription) {
		super(prescription);
		this.procedure = procedure;
	}

	public Procedure getProcedure() {
		return this.procedure;
	}

	public void setProcedure(Procedure procedure) {
		this.procedure = procedure;
	}
	
	@Override
	protected CommonDataInterface getConnonData() {
	    return this.procedure;
	}

}