package eu.dedalus.prescriptionsolver;
import org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.optaplanner.core.api.domain.solution.PlanningSolution(autoDiscoverMemberType = org.optaplanner.core.api.domain.autodiscover.AutoDiscoverMemberType.FIELD)
@javax.xml.bind.annotation.XmlRootElement
@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)
public class PrescriptionSolution implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("lista delle ricette")
	@org.optaplanner.core.api.domain.valuerange.ValueRangeProvider(id = "prescriptionReference")
	private java.util.List<eu.dedalus.prescriptionsolver.Prescription> prescriptions;
	@org.kie.api.definition.type.Label("Generated Planner score field")
	@javax.annotation.Generated({"org.optaplanner.workbench.screens.domaineditor.client.widgets.planner.PlannerDataObjectEditor"})
	@org.optaplanner.core.api.domain.solution.PlanningScore
	@javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter(org.optaplanner.persistence.jaxb.api.score.buildin.hardsoft.HardSoftScoreJaxbXmlAdapter.class)
	private org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore score;

	@org.kie.api.definition.type.Label("lista dei farmaci prescritti")
	private java.util.List<eu.dedalus.prescriptionsolver.PrescriptionDrug> drugs;

	@org.kie.api.definition.type.Label(value = "lista degli accertamenti prescritti")
	private java.util.List<eu.dedalus.prescriptionsolver.PrescriptionProcedure> procedures;
	
	
	@org.kie.api.definition.type.Label(value = "lista dei ricoveri prescritti")
	private java.util.List<eu.dedalus.prescriptionsolver.PrescriptionAdmission> admissions;

	public PrescriptionSolution() {
	}

	public java.util.List<eu.dedalus.prescriptionsolver.Prescription> getPrescriptions() {
		return this.prescriptions;
	}

	public void setPrescriptions(
			java.util.List<eu.dedalus.prescriptionsolver.Prescription> prescriptions) {
		this.prescriptions = prescriptions;
	}

	public HardMediumSoftScore getScore() {
		return this.score;
	}

	public void setScore(HardMediumSoftScore score) {
		this.score = score;
	}

	public java.util.List<eu.dedalus.prescriptionsolver.PrescriptionDrug> getDrugs() {
		return this.drugs;
	}

	public void setDrugs(
			java.util.List<eu.dedalus.prescriptionsolver.PrescriptionDrug> drugs) {
		this.drugs = drugs;
	}

	public java.util.List<eu.dedalus.prescriptionsolver.PrescriptionProcedure> getProcedures() {
		return this.procedures;
	}

	public void setProcedures(
			java.util.List<eu.dedalus.prescriptionsolver.PrescriptionProcedure> procedures) {
		this.procedures = procedures;
	}
    
    public java.util.List<eu.dedalus.prescriptionsolver.PrescriptionAdmission> getAdmissions() {
		return this.admissions;
	}

	public void setAdmissions(
			java.util.List<eu.dedalus.prescriptionsolver.PrescriptionAdmission> admissions) {
		this.admissions = admissions;
	}
	
	public PrescriptionSolution(
			java.util.List<eu.dedalus.prescriptionsolver.Prescription> prescriptions,
			org.optaplanner.core.api.score.buildin.hardmediumsoft.HardMediumSoftScore score,
			java.util.List<eu.dedalus.prescriptionsolver.PrescriptionDrug> drugs,
			java.util.List<eu.dedalus.prescriptionsolver.PrescriptionProcedure> procedures,
			java.util.List<eu.dedalus.prescriptionsolver.PrescriptionAdmission> admissions) {
		this.prescriptions = prescriptions;
		this.score = score;
		this.drugs = drugs;
		this.procedures = procedures;
		this.admissions = admissions;
	}

}